const imageUrl = "https://picsum.photos/300/150";
const mapData = [
    {
      "name": "Connaught Place Store",
      "country": "India",
      "latitude": 28.7041,
      "longitude": 77.1025,
      "button_text": "Read More",
      "label": "A",
      "label_color": "green",
      "is_active": true,
      "type": "point",
      "content": "Our Delhi store offers premium electronics, fashion, and home appliances in the heart of Connaught Place.",
      "imageUrl": imageUrl
    },
    {
      "name": "Mumbai Flagship Store",
      "country": "India",
      "latitude": 19.7515,
      "longitude": 75.7139,
      "button_text": "Read More",
      "label": "B",
      "label_color": "blue",
      "is_active": true,
      "type": "new",
      "content": "A flagship store in South Mumbai showcasing luxury fashion, gadgets, and lifestyle essentials.",
      "imageUrl": imageUrl
    },
    {
      "name": "Chennai Express Outlet",
      "country": "India",
      "latitude": 11.1271,
      "longitude": 78.6569,
      "button_text": "Read More",
      "label": "C",
      "label_color": "red",
      "is_active": false,
      "type": "upcoming",
      "content": "Opening soon in Chennai with a modern experience center and in-store pickup options.",
      "imageUrl": imageUrl
    },
    {
      "name": "San Francisco Bay Store",
      "country": "United States",
      "latitude": 36.7783,
      "longitude": -119.4179,
      "button_text": "Read More",
      "label": "A",
      "label_color": "yellow",
      "is_active": false,
      "type": "point",
      "content": "A tech-driven store in California, specializing in Apple products, smart devices, and accessories.",
      "imageUrl": imageUrl
    },
    {
      "name": "Times Square Showroom",
      "country": "United States",
      "latitude": 40.7128,
      "longitude": -74.006,
      "button_text": "Read More",
      "label": "B",
      "label_color": "purple",
      "is_active": true,
      "type": "point",
      "content": "Located in Manhattan, this showroom features luxury fashion, designer watches, and flagship collections.",
      "imageUrl": imageUrl
    },
    {
      "name": "Dallas Superstore",
      "country": "United States",
      "latitude": 31.9686,
      "longitude": -99.9018,
      "label": "C",
      "label_color": "blue",
      "is_active": false,
      "type": "point",
      "content": "Our Texas superstore brings together furniture, electronics, and everyday essentials under one roof.",
      "imageUrl": imageUrl
    },
    {
      "name": "Sydney Harbour Store",
      "country": "Australia",
      "latitude": -31.2532,
      "longitude": 146.9211,
      "label": "D",
      "label_color": "red",
      "is_active": true,
      "type": "point",
      "content": "Located near Sydney Harbour, this outlet offers outdoor gear, surf equipment, and lifestyle products.",
      "imageUrl": imageUrl
    },
    {
      "name": "Brisbane Central Mall Store",
      "country": "Australia",
      "latitude": -20.9176,
      "longitude": 142.7028,
      "label": "A",
      "label_color": "green",
      "is_active": true,
      "type": "point",
      "content": "Our Brisbane store offers a curated selection of fashion, health, and beauty products.",
      "imageUrl": imageUrl
    },
    {
      "name": "Perth City Plaza",
      "country": "Australia",
      "latitude": -31.95563,
      "longitude": 115.85879,
      "label": "B",
      "label_color": "yellow",
      "is_active": false,
      "type": "new",
      "content": "A brand-new Perth shopping plaza featuring boutique cafés, lifestyle shops, and technology counters.",
      "imageUrl": imageUrl
    },
    {
      "name": "Toronto Downtown Store",
      "country": "Canada",
      "latitude": 51.2538,
      "longitude": -85.3232,
      "label": "C",
      "label_color": "red",
      "is_active": true,
      "type": "point",
      "content": "Our Toronto outlet features electronics, fashion, and exclusive winter collections.",
      "imageUrl": imageUrl
    },
    {
      "name": "Montreal Lifestyle Outlet",
      "country": "Canada",
      "latitude": 52.9399,
      "longitude": -73.5491,
      "label": "A",
      "label_color": "blue",
      "is_active": false,
      "type": "point",
      "content": "A Montreal store inspired by French lifestyle, offering fashion, gourmet food, and décor.",
      "imageUrl": imageUrl
    },
    {
      "name": "Munich Luxury Hub",
      "country": "Germany",
      "latitude": 48.7904,
      "longitude": 11.4979,
      "label": "B",
      "label_color": "purple",
      "is_active": true,
      "type": "point",
      "content": "Located in Bavaria, this hub is known for luxury watches, German auto showcases, and premium products.",
      "imageUrl": imageUrl
    },
    {
      "name": "Berlin Flagship Center",
      "country": "Germany",
      "latitude": 52.52,
      "longitude": 13.405,
      "label": "D",
      "label_color": "green",
      "is_active": true,
      "type": "point",
      "content": "Berlin’s flagship store, featuring modern European fashion, art-inspired collections, and technology.",
      "imageUrl": imageUrl
    }
  ];
  
// const mapData = [
//     {
//         "name": "Delhi",
//         "country": "India",
//         "latitude": 28.7041,
//         "longitude": 77.1025,
//         "button_text": "Read More",
//         "label": "A",
//         "label_color": "red",
//         "is_active": true,
//         "type": "point",
//         "content": "Real Property Associates Inc. is dedicated to the principle of equal access for people with disabilities in compliance with the Americans with Disabilities Act (ADA) and HUD guidelines."
//     },
//     {
//         "name": "Maharashtra",
//         "country": "India",
//         "latitude": 19.7515,
//         "longitude": 75.7139,
//         "button_text": "Read More",
//         "label": "B",
//         "label_color": "blue",
//         "is_active": true,
//         "type": "new",
//         "content": "Real Property Associates Inc. is dedicated to the principle of equal access for people with disabilities in compliance with the Americans with Disabilities Act (ADA) and HUD guidelines."
//     },
//     {
//         "name": "Tamil Nadu",
//         "country": "India",
//         "latitude": 11.1271,
//         "longitude": 78.6569,
//         "button_text": "Read More",
//         "label": "A",
//         "label_color": "red",
//         "is_active": true,
//         "type": "upcoming",
//         "content": "Real Property Associates Inc. is dedicated to the principle of equal access for people with disabilities in compliance with the Americans with Disabilities Act (ADA) and HUD guidelines."
//     },
//     {
//         "name": "California",
//         "country": "United States",
//         "latitude": 36.7783,
//         "longitude": -119.4179,
//         "button_text": "Read More",
//         "label": "A",
//         "label_color": "red",
//         "is_active": false,
//         "type": "point",
//         "content": "Real Property Associates Inc. is dedicated to the principle of equal access for people with disabilities in compliance with the Americans with Disabilities Act (ADA) and HUD guidelines."
//     },
//     {
//         "name": "New York",
//         "country": "United States",
//         "latitude": 40.7128,
//         "longitude": -74.006,
//         "button_text": "Read More",
//         "label": "B",
//         "label_color": "blue",
//         "is_active": false,
//         "type": "point",
//         "content": "Real Property Associates Inc. is dedicated to the principle of equal access for people with disabilities in compliance with the Americans with Disabilities Act (ADA) and HUD guidelines."
//     },
//     {
//         "name": "Texas",
//         "country": "United States",
//         "latitude": 31.9686,
//         "longitude": -99.9018,
//         "label": "C",
//         "label_color": "green",
//         "is_active": false,
//         "type": "point",
//         "content": "Real Property Associates Inc. is dedicated to the principle of equal access for people with disabilities in compliance with the Americans with Disabilities Act (ADA) and HUD guidelines."
//     },
//     {
//         "name": "Australia",
//         "country": "Australia",
//         "latitude": -31.2532,
//         "longitude": 146.9211,
//         "label": "A",
//         "label_color": "red",
//         "is_active": true,
//         "type": "point",
//         "content": "Real Property Associates Inc. is dedicated to the principle of equal access for people with disabilities in compliance with the Americans with Disabilities Act (ADA) and HUD guidelines."
//     },
//     {
//         "name": "Queensland",
//         "country": "Australia",
//         "latitude": -20.9176,
//         "longitude": 142.7028,
//         "label": "B",
//         "label_color": "blue",
//         "is_active": true,
//         "type": "point",
//         "content": "Real Property Associates Inc. is dedicated to the principle of equal access for people with disabilities in compliance with the Americans with Disabilities Act (ADA) and HUD guidelines."
//     },
//     {
//         "name": "pearth",
//         "country": "Australia",
//         "latitude": -31.95563,
//         "longitude": 115.85879,
//         "label": "C",
//         "label_color": "green",
//         "is_active": true,
//         "type": "new",
//         "content": "Real Property Associates Inc. is dedicated to the principle of equal access for people with disabilities in compliance with the Americans with Disabilities Act (ADA) and HUD guidelines."
//     },
//     {
//         "name": "Ontario",
//         "country": "Canada",
//         "latitude": 51.2538,
//         "longitude": -85.3232,
//         "label": "A",
//         "label_color": "red",
//         "is_active": true,
//         "type": "point",
//         "content": "Real Property Associates Inc. is dedicated to the principle of equal access for people with disabilities in compliance with the Americans with Disabilities Act (ADA) and HUD guidelines."
//     },
//     {
//         "name": "Quebec",
//         "country": "Canada",
//         "latitude": 52.9399,
//         "longitude": -73.5491,
//         "label": "B",
//         "label_color": "blue",
//         "is_active": true,
//         "type": "point",
//         "content": "Real Property Associates Inc. is dedicated to the principle of equal access for people with disabilities in compliance with the Americans with Disabilities Act (ADA) and HUD guidelines."
//     },
//     {
//         "name": "Bavaria",
//         "country": "Germany",
//         "latitude": 48.7904,
//         "longitude": 11.4979,
//         "label": "A",
//         "label_color": "red",
//         "is_active": true,
//         "type": "point",
//         "content": "Real Property Associates Inc. is dedicated to the principle of equal access for people with disabilities in compliance with the Americans with Disabilities Act (ADA) and HUD guidelines."
//     },
//     {
//         "name": "Berlin",
//         "country": "Germany",
//         "latitude": 52.52,
//         "longitude": 13.405,
//         "label": "B",
//         "label_color": "blue",
//         "is_active": true,
//         "type": "point",
//         "content": "Real Property Associates Inc. is dedicated to the principle of equal access for people with disabilities in compliance with the Americans with Disabilities Act (ADA) and HUD guidelines."
//     }
// ];